version: '3.3'
services:
  nginx:
    container_name: update-server
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8083:80"
    image: nginx
